# 异步函数 捕获异常

在回调函数里面，如果有异常的话，在最外层包一层 try catch 是捕获不到异常的，因为不在一个上下文。必须在回调函数里面加一层 try catch 捕获异常

```ts
try {
  fs.readFile(url, (res) => {
    try{
      xxxxx
    }catch(err){

    }
    xxxxx;
    // if get error outside can't catch the error
  });
} catch (err) {
  console.log(err);
}
```
